version: "3.3"

services:

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/postgres/init_setup.sql:/docker-entrypoint-initdb.d/init_setup.sql
    environment:
      POSTGRES_PASSWORD: adminadmin
    ports:
      - 5432:5432

  mqtt:
    image: eclipse-mosquitto:latest
    user: "1000:1000"
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config
      - ./docker/mosquitto/log:/mosquitto/log
      - ./docker/mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
      - 8080:8080
      - 8883:8883
      - 8884:8884
      - 9001:9001

  web:
    restart: unless-stopped
    build: ./webapp/weather_station
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - "8000"
    depends_on:
      - db
      - redis
      - mqtt
    volumes:
      - ./webapp/weather_station/:/usr/scr/webapp/
    ports:
      - 8000:8000

  redis:
    image: redis
    restart: unless-stopped
    volumes:
      - redisdata:/data
    ports:
      - 6379:6379

  caddy:
    image: caddy:latest
    restart: unless-stopped
    network_mode: host
      #   ports:
      #     - 80:80
      #     - 443:443
      #     - "443:443/udp"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  pgdata:
  redisdata:
  caddy_data:
  caddy_config:
