# Generated by Django 4.2.5 on 2023-10-13 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_alter_weather_stations_user'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='light_intensity',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='weather',
            name='wind_speed',
        ),
        migrations.AddField(
            model_name='weather',
            name='data',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='station', to='map.weather_stations'),
        ),
    ]
