# Generated by Django 4.2.5 on 2023-09-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
