# Generated by Django 4.2.5 on 2023-10-03 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_weather_stations_user'),
        ('dashboard', '0002_alter_weather_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weather',
            name='weather_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station', to='map.weather_stations'),
        ),
    ]
